### ISSUE TITLE
Monitormode

### ISSUE THREAD

**Issue by homeauto** [shandongtlb/MI9-Nethunter-Project#1]
Hi
When i try to put my external wifi-card in monitormode it doesn't work
if i run airmon-ng start wlan1 it doesn't start if i run iwconfig wlan1 mode monitor it says
Error for wireless request "Set Mode" (8B06) :
    SET failed on device wlan1 ; Operation not supported.
lsusb find my card  Qualcomm Atheros Communications AR9271
What am i missing?
Thanks in advanced

**Comment by shandongtlb** [comment]
Wow, if you used Xiaomi phone, you should run `airmon-ng start wlan2`  instead of `airmon-ng start wlan1`

**Comment by shandongtlb** [comment]
Sorry, I ’ve been busy recently,,,,, so I didn’t reply to you in time.XD
