### ISSUE TITLE
Kernel tutorial 

### ISSUE THREAD

**Issue by Naster17** [shandongtlb/MI9-Nethunter-Project#10]
Hi, I wanted to ask how you collect nucleus, I want to do the core for Redmi Note 9 Pro

**Comment by plant7403** [comment]
Hi 👋
I'm not sure, but it can be this:
Take your kernel's source
Add this patch https://github.com/shandongtlb/MI9-Nethunter-Project/blob/master/MI9-nethunter-4.14.patch
Compile the kernel
Repack your boot image and replace the kernel there
Flash the new boot image

**Comment by Naster17** [comment]
is this patch for MI9?

**Comment by Naster17** [comment]
Can I have detailed instructions?

**Comment by plant7403** [comment]
> Can I have detailed instructions?

It's all I know 😅
It's for mi 9, and I'm not 100% sure you can use it for your device
But you can try 😁 (with your kernel source of course😅)
