### ISSUE TITLE
Feedback. Screen is even worse than before

### ISSUE THREAD

**Issue by plant7403** [shandongtlb/MI9-Nethunter-Project#2]
With last 3 updates the screen got worse and worse 
Also on the last version I saw a spontaneous rebooting
But in general: God, bless those wonderful people, I wish them to have a lot of money, health, girls... Etc 😂
Thank you very much for your work ❤️

**Comment by shandongtlb** [comment]
> With last 3 updates the screen got worse and worse
> Also on the last version I saw a spontaneous rebooting
> But in general: God, bless those wonderful people, I wish them to have a lot of money, health, girls... Etc 😂
> Thank you very much for your work ❤️

In the last version, I fixed the screen and fingerprint. As for the spontaneous rebooting you said, I have not encountered

**Comment by shandongtlb** [comment]
> With last 3 updates the screen got worse and worse
> Also on the last version I saw a spontaneous rebooting
> But in general: God, bless those wonderful people, I wish them to have a lot of money, health, girls... Etc 😂
> Thank you very much for your work ❤️

please flash v17

**Comment by plant7403** [comment]
![Screenshot_2020-08-14-06-21-56-930_com.android.settings.jpg](https://user-images.githubusercontent.com/24483751/90196623-7ef68580-ddf6-11ea-9f95-39c04da6b893.jpg)
V17, I was not kidding, even more not working sensor than before 😬

**Comment by shandongtlb** [comment]
I am using MIUI12.0.3 stable version, everything is normal.....
Allow me to use it for a while and wait for this problem to reappear and then fix it

**Comment by plant7403** [comment]
> I am using MIUI12.0.3 stable version, everything is normal.....
> Allow me to use it for a while and wait for this problem to reappear and then fix it

I use MIUI chinese beta, by the way☝️

**Comment by shandongtlb** [comment]
> > I am using MIUI12.0.3 stable version, everything is normal.....
> > Allow me to use it for a while and wait for this problem to reappear and then fix it
> 
> I use MIUI chinese beta, by the way☝️

Yes I am, me too.  MIUI chinese stable 12.0.3
