### ISSUE TITLE
FOD doesnt work on MIUI 12 stable + power button bug

### ISSUE THREAD

**Issue by Darkwulfer** [shandongtlb/MI9-Nethunter-Project#3]
Hello, i tried your kernel but it had two bugs. First one is the fod dim doesnt work and wont lit up with finger put it on and when i turn on screen its too dim and wont recognize my fp. Second bug is with power button. When you hold power button and leave it the power menu will go off without touch any of those options in there like shut down or reboot. I must hold it and click the option and then leave it. Can you please fix these two? I wanna try this kernel but with these two annoying bugs its unusable 👎 Thanks.

**Comment by shandongtlb** [comment]
Emmm, I use MIUI12 chinese stable 12.0.3, at present, there is no problem you mentioned.
Are you installing some xposed modules that cause FP not to work? And you go and have a look at /system/build.prop  ro.fod.dimlayer.enable=true or false. If it is =true, please change to =false.
As for the power button bug you said, I have never encountered it

**Comment by Darkwulfer** [comment]
I will try it on miui eu rom beta because i change it from stable but i think it will be the same. I will let you know even with logcat if you want.

**Comment by shandongtlb** [comment]
> I will try it on miui eu rom beta because i change it from stable but i think it will be the same. I will let you know even with logcat if you want.

Okay okay

**Comment by Darkwulfer** [comment]
I updated to latest eu weekly rom and it works like you said which is weird. Your kernel works great but one feature i am missing. Can you add layer for fingeprint as magisk module like quantic kernel have? FP works like with stock so its lit up automatically even with screen off.

**Comment by shandongtlb** [comment]
> I updated to latest eu weekly rom and it works like you said which is weird. Your kernel works great but one feature i am missing. Can you add layer for fingeprint as magisk module like quantic kernel have? FP works like with stock so its lit up automatically even with screen off.


I've made modules, integrated into the kernel at v17, and at present, fingerprints are working well.
![Screenshot_2020-08-19-00-36-28-611_com topjohnwu magisk](https://user-images.githubusercontent.com/40312509/90540960-8500b380-e1b4-11ea-9010-3f936f4bba85.jpg)
![Screenshot_2020-08-19-00-36-54-338_bin mt plus](https://user-images.githubusercontent.com/40312509/90540979-8a5dfe00-e1b4-11ea-9d04-2640cced7976.jpg)

**Comment by Darkwulfer** [comment]
Thats weird, i dont have this module installed with kernel. :-(

**Comment by plant7403** [comment]
> Thats weird, i dont have this module installed with kernel. :-(

I have but bugs are still present 😟

**Comment by Darkwulfer** [comment]
Can you provide me the module alone as flash zip file to magisk? I flashed your kernel few times but still no module appear in magisk manager :/

**Comment by shandongtlb** [comment]
> Can you provide me the module alone as flash zip file to magisk? I flashed your kernel few times but still no module appear in magisk manager :/


You can modify it manually first, and I'll talk about it later, I have been busy recently.....

look at /system/build.prop    ro.fod.dimlayer.enable=true   modify true to false

**Comment by Darkwulfer** [comment]
> > Can you provide me the module alone as flash zip file to magisk? I flashed your kernel few times but still no module appear in magisk manager :/
> 
> You can modify it manually first, and I'll talk about it later, I have been busy recently.....
> 
> look at /system/build.prop ro.fod.dimlayer.enable=true modify true to false

Yes i modified the build.prop line with fod dimlayer and FOD works but i must wake up the phone with power button to use FOD. In stock or for example in quantic kernels i can use the fod without waking the phone with power button. Quantic kernel have magisk module for using fod without waking the phone with power button. I hope you understand me correctly :D U can close this problem after u answer or without answer because it doesnt match up the title anymore.

**Comment by shandongtlb** [comment]
> > > Can you provide me the module alone as flash zip file to magisk? I flashed your kernel few times but still no module appear in magisk manager :/
> > 
> > 
> > You can modify it manually first, and I'll talk about it later, I have been busy recently.....
> > look at /system/build.prop ro.fod.dimlayer.enable=true modify true to false
> 
> Yes i modified the build.prop line with fod dimlayer and FOD works but i must wake up the phone with power button to use FOD. In stock or for example in quantic kernels i can use the fod without waking the phone with power button. Quantic kernel have magisk module for using fod without waking the phone with power button. I hope you understand me correctly :D U can close this problem after u answer or without answer because it doesnt match up the title anymore.

Ok, I get it. First of all, I am very sorry that my English is not good

But my mi9 device can be woken up by fingerprint like Quantic kernel instead of having to use the power button
![IMG_0169 00_00_00-00_00_30](https://user-images.githubusercontent.com/40312509/90759111-919b1e00-e312-11ea-8d49-2b54ececb423.gif)

**Comment by Darkwulfer** [comment]
No problem at all with language barrier. My english isnt best either :D 
Your device can be wake up with finger because u have that magisk module installed with kernel that didnt install for me and thats the problem i think. If you have telegram or kernel group on telegram, we can close this issue and move over there for discussion.

**Comment by shandongtlb** [comment]
> No problem at all with language barrier. My english isnt best either :D
> Your device can be wake up with finger because u have that magisk module installed with kernel that didnt install for me and thats the problem i think. If you have telegram or kernel group on telegram, we can close this issue and move over there for discussion.

https://t.me/sudoMGK

**Comment by shandongtlb** [comment]
> > Thats weird, i dont have this module installed with kernel. :-(
> 
> I have but bugs are still present

I have released v18, you should flash it to fix touchscreen
