### ISSUE TITLE
HID ATTACK

### ISSUE THREAD

**Issue by nethunterkaliandroid** [shandongtlb/MI9-Nethunter-Project#6]
I am using miui12 eu rom I have flashed latest release of nethunter kernel. Everything is fine except HID. I can use usb keyboard very well also duckhunter HID attacks. But I can't use cmd attack. It's not working. I can't find a solution. So I want to help me...
Thanks for kernel.
Please reply me :)

**Comment by shandongtlb** [comment]
Sorry, I can only solve the bug in the kernel for you. As for how to use it, I can't help you

**Comment by nethunterkaliandroid** [comment]
It's the kernel's bug already the I am using nethunter's recent release and no one have the problem. This problem kernel's bug. Please fix this just duckhunter working and mi 9 doesn't need to flash this kernel for duckhunter hid attack please fix this in your kernel because the kernel is useless now :)
Thanks for everything I think you are a good developer

**Comment by shandongtlb** [comment]
> It's the kernel's bug already the I am using nethunter's recent release and no one have the problem. This problem kernel's bug. Please fix this just duckhunter working and mi 9 doesn't need to flash this kernel for duckhunter hid attack please fix this in your kernel because the kernel is useless now :)
> Thanks for everything I think you are a good developer


The hid attcak is indeed not used, but IEEE80211 wireless injection, otg external network card and sysvipc still need kernel support

**Comment by nethunterkaliandroid** [comment]
I know it I have tried to build a kernel for another device but I don't know whg Windows CMD not working. It says attack launched but don't send anything to the computer. The external adapters are very expensive in my country. For this reason it is useless for me unfortunately. Thanks for sysvipc. It seems I cannot do anything from mobile phone. Maybe android trojans useful. Other tools need kali linux. Because android's screen very small. Just wifi attack can be used. Otherwise andrax and nethunter both of them are useless. Thanks developer. I wish you success in your life
Best regards

**Comment by shandongtlb** [comment]
> I know it I have tried to build a kernel for another device but I don't know whg Windows CMD not working. It says attack launched but don't send anything to the computer. The external adapters are very expensive in my country. For this reason it is useless for me unfortunately. Thanks for sysvipc. It seems I cannot do anything from mobile phone. Maybe android trojans useful. Other tools need kali linux. Because android's screen very small. Just wifi attack can be used. Otherwise andrax and nethunter both of them are useless. Thanks developer. I wish you success in your life
> Best regards

Thanks
You can use droidducky app and edit the hid script file by yourself to complete the windows cmd attack

**Comment by nethunterkaliandroid** [comment]
> > I know it I have tried to build a kernel for another device but I don't know whg Windows CMD not working. It says attack launched but don't send anything to the computer. The external adapters are very expensive in my country. For this reason it is useless for me unfortunately. Thanks for sysvipc. It seems I cannot do anything from mobile phone. Maybe android trojans useful. Other tools need kali linux. Because android's screen very small. Just wifi attack can be used. Otherwise andrax and nethunter both of them are useless. Thanks developer. I wish you success in your life
> > Best regards
> 
> Thanks
> You can use droidducky app and edit the hid script file by yourself to complete the windows cmd attack

I know it. Already duckhunter HID is working in nethunter app I don't need the droidducky. But I am wondering why the Windows CMD not works. It's not a problem. I am just wondering. It's nonsense I don't understand why that is not working while everything is completed. I am wondering cause of the error. 
Thanks for everything
